In [ ]:
import numpy as np

In [ ]:
arr1=np.array([[324,34,46,56,65,22],[325,56,23,66,32,44],[326,44,23,56,22,67,],[327,89,44,24,23,12],[328,45,62,11,89,45]])

In [ ]:
arr1.dtype


dtype('int64')

In [ ]:
#2 find total students
(r,c)=arr1.shape
print("Total Students: ",r)

Total Students:  5


In [ ]:
#3 print all studetns roll nos
print("All Student Roll No.",arr1[::,0])

All Student Roll No. [324 325 326 327 328]


In [ ]:
#4 print subject 1 marks
print("Subject 1 marks:",arr1[::,1])

Subject 1 marks: [34 56 44 89 45]


In [ ]:
#5 find min marks of subject 2
print("Min marks in subject 2:",np.min(arr1[::,2]))

Min marks in subject 2: 23


In [ ]:
#6 find max marks of subject 3
print("Max marks in subject 3:",np.max(arr1[::,3]))

Max marks in subject 3: 66


In [ ]:
#7 find marks of all subjects
print("Marks of all subjects are:\n",arr1[::,1::])

Marks of all subjects are:
 [[34 46 56 65 22]
 [56 23 66 32 44]
 [44 23 56 22 67]
 [89 44 24 23 12]
 [45 62 11 89 45]]


In [ ]:
#8 find the avg marks of all students
print("Sum of all subjects marks are:\n",arr1[::,0])
avg=np.mean(arr1[::,1::],axis=1)
print(np.round(avg,1))
print(np.round(avg))


Sum of all subjects marks are:
 [324 325 326 327 328]
[44.6 44.2 42.4 38.4 50.4]
[45. 44. 42. 38. 50.]


In [ ]:
#9 find roll no who got min marks in subject 2
i=np.argmin(arr1[:,2])
print("Roll no who got minimum marks in subject 2",arr1[i,0])


Roll no who got minimum marks in subject 2 325


In [ ]:
def prepared_array():
  rows,cold=map(int, input().split())
  list1=[]
  for _ in range(rows):
    row = list(map(int, input().split())) #f"Enter {cols) elements for row { + 1) separated by space:
    list1.extend(row)
  arr1= np.array (list1).reshape(rows, cols)
  return arr1
# Create and display the NumPy array
arr1 =prepared_array()
#Display array information
#print("\nNumPy Array:")
print(arr1)
#print("\nArray Information:")
print(arr1.ndim) #Dimensions (ndim)
print(arr1.shape) #Shape:
print(arr1.size) #Size