In [ ]:
import numpy as np

# Inputting the matrices
print("Enter the First Matrix A (3 rows, 3 columns): ")
matrix_a = np.array([list(map(int, input().split())) for i in range(3)])
print("Enter the Second Matrix B (3 rows, 3 columns): ")
matrix_b = np.array([list(map(int, input().split())) for i in range(3)])

# Addition
add_result = np.add(matrix_a, matrix_b)
print("Addition of (A+B) is: ")
print(add_result)

# Subtraction
sub_result = np.subtract(matrix_a, matrix_b)
print("Subtraction of (A-B) is: ")
print(sub_result)

# Multiplication
mul_result = np.multiply(matrix_a, matrix_b)
print("Multiplication of (A*B) is: ")
print(mul_result)


# Dot
dot_result = np.dot(matrix_a, matrix_b)
print("Dot of (A*B): ")
print(dot_result)

# Transpose
t_a = matrix_a.T
t_b = matrix_b.T
print("Transpose of A: ")
print(t_a)
print("Transpose of B: ")
print(t_b)

Enter the First Matrix A (3 rows, 3 columns): 
1 2 3 
4 5 6
7 8 6
Enter the Second Matrix B (3 rows, 3 columns): 
11 12 13
14 15 16
17 18 19
Addition of (A+B) is: 
[[12 14 16]
 [18 20 22]
 [24 26 25]]
Subtraction of (A-B) is: 
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -13]]
Multiplication of (A*B) is: 
[[ 11  24  39]
 [ 56  75  96]
 [119 144 114]]
Dot of (A*B): 
[[ 90  96 102]
 [216 231 246]
 [291 312 333]]
Transpose of A: 
[[1 4 7]
 [2 5 8]
 [3 6 6]]
Transpose of B: 
[[11 14 17]
 [12 15 18]
 [13 16 19]]


In [ ]:
np.hstack((matrix_a, matrix_b))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  6, 17, 18, 19]])

In [ ]:
np.vstack((matrix_a, matrix_b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  6],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])